### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mikepurvis** [shadow-robot/ros_control_robot#25]
The license for this package was set to GPL in https://github.com/shadow-robot/ros_control_robot/commit/ad83ada353003162eaa0c3609a23933c344193bf#diff-34ae68f4adad56c25c5bc05dcb64794eR9. Was this an intentional choice?

Either way, would you consider relicensing under BSD or Apache 2.0?

**Comment by toliver** [comment]
Thanks @mikepurvis 
We will change it to BSD.
The reason for the change was that we use GPL as our default license when we create a new public package. We probably should have kept the original one in this case.

**Comment by mikepurvis** [comment]
No worries, thanks. My intent is to build on it anyway, and I just wanted to know if I should be starting my (non-GPL) implementation from scratch of if it was okay to build on this work.

**Comment by toliver** [comment]
Done via https://github.com/shadow-robot/ros_control_robot/pull/28
